name: modulo Deployment Azure

on: [push]

env:
  AZURE_WEBAPP_NAME: JustCook   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './JustCook'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'

    - name: npm install, build, and test
    - run: npm install
    - run: npm test

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: JustCook-artifact
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: JustCook-artifact

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
