name: Main
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      run: npm install
    - run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3
    - uses: akhileshns/heroku-deploy@v3.7.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "justcook"
        heroku_email: "denise.comincioli@studenti.unitn.it"
